#!/usr/bin/env bash
set +e

mkdir -p /tmp/storage/app
mkdir -p /tmp/storage/framework/cache
mkdir -p /tmp/storage/framework/cache/data
mkdir -p /tmp/storage/framework/views
mkdir -p /tmp/storage/framework/sessions
mkdir -p /tmp/storage/logs

export APP_STORAGE_PATH=/tmp/storage

php artisan schedule:run >> /dev/null 2>&1
